# Form implementation generated from reading ui file 'ui_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(401, 81)
        self.line = QtWidgets.QLineEdit(parent=Dialog)
        self.line.setGeometry(QtCore.QRect(10, 20, 381, 21))
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(10, 0, 121, 21))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.cancel = QtWidgets.QPushButton(parent=Dialog)
        self.cancel.setGeometry(QtCore.QRect(320, 50, 75, 23))
        self.cancel.setObjectName("cancel")
        self.ok = QtWidgets.QPushButton(parent=Dialog)
        self.ok.setGeometry(QtCore.QRect(240, 50, 75, 23))
        self.ok.setObjectName("ok")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Выбор папки"))
        self.label.setText(_translate("Dialog", "Введите адрес папки"))
        self.cancel.setText(_translate("Dialog", "Cancel"))
        self.ok.setText(_translate("Dialog", "OK"))
