# Form implementation generated from reading ui file 'ui_widget.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(601, 401)
        self.image = QtWidgets.QLabel(parent=Form)
        self.image.setGeometry(QtCore.QRect(10, 50, 581, 291))
        self.image.setObjectName("image")
        self.line = QtWidgets.QLineEdit(parent=Form)
        self.line.setGeometry(QtCore.QRect(10, 10, 541, 31))
        self.line.setObjectName("line")
        self.ok_btn = QtWidgets.QPushButton(parent=Form)
        self.ok_btn.setGeometry(QtCore.QRect(560, 10, 31, 31))
        self.ok_btn.setObjectName("ok_btn")
        self.prev_btn = QtWidgets.QPushButton(parent=Form)
        self.prev_btn.setGeometry(QtCore.QRect(90, 350, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        self.prev_btn.setFont(font)
        self.prev_btn.setObjectName("prev_btn")
        self.next_btn = QtWidgets.QPushButton(parent=Form)
        self.next_btn.setGeometry(QtCore.QRect(250, 350, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        self.next_btn.setFont(font)
        self.next_btn.setObjectName("next_btn")
        self.first_btn = QtWidgets.QPushButton(parent=Form)
        self.first_btn.setGeometry(QtCore.QRect(10, 360, 71, 21))
        self.first_btn.setObjectName("first_btn")
        self.last_btn = QtWidgets.QPushButton(parent=Form)
        self.last_btn.setGeometry(QtCore.QRect(330, 360, 71, 21))
        self.last_btn.setObjectName("last_btn")
        self.slide_show_btn = QtWidgets.QPushButton(parent=Form)
        self.slide_show_btn.setGeometry(QtCore.QRect(170, 350, 71, 41))
        self.slide_show_btn.setObjectName("slide_show_btn")
        self.turn_r_btn = QtWidgets.QPushButton(parent=Form)
        self.turn_r_btn.setGeometry(QtCore.QRect(410, 350, 51, 41))
        self.turn_r_btn.setObjectName("turn_r_btn")
        self.turn_l_btn = QtWidgets.QPushButton(parent=Form)
        self.turn_l_btn.setGeometry(QtCore.QRect(470, 350, 51, 41))
        self.turn_l_btn.setObjectName("turn_l_btn")
        self.del_bnt = QtWidgets.QPushButton(parent=Form)
        self.del_bnt.setGeometry(QtCore.QRect(530, 360, 61, 23))
        self.del_bnt.setObjectName("del_bnt")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.image.setText(_translate("Form", "TextLabel"))
        self.ok_btn.setText(_translate("Form", "ОК"))
        self.prev_btn.setText(_translate("Form", "←"))
        self.next_btn.setText(_translate("Form", "→"))
        self.first_btn.setText(_translate("Form", "Первый"))
        self.last_btn.setText(_translate("Form", "Последний"))
        self.slide_show_btn.setText(_translate("Form", "Слайд-шоу"))
        self.turn_r_btn.setText(_translate("Form", "По час."))
        self.turn_l_btn.setText(_translate("Form", "Против"))
        self.del_bnt.setText(_translate("Form", "Удалить"))
